### PR TITLE
Add File Storage

### PR DESCRIPTION
**Pull request by LarsJK**
Adds file storage ref: #6 

This reads from disk every time you read, I could add a memory cache but is that what is meant by Hybrid Storage?

### CODE REVIEW

**Comment by khoi** [comment]
Hi @LarsJK, thank you for contributing to the project. Writing the whole `internalStorage` down to disk would introduce a huge performance bottleneck when the users want to set or retrieve individual item.

I was thinking of the approach of each `Item` in the Storage would have its own separated file written on disk.

What do you think?

**Comment by LarsJK** [comment]
Sounds good!

I thought maybe the amount of data would be to small to make a difference. I also considered reading only once and keeping a in-memory representation, and that would speed up writes.

I can definitely change it to write to different files tho. I can keep a subfolder in the documents directory called "StatsD_FileStorage" and keep the files named by key in that directory?
I can delete the whole directory in removeAll..

Sounds good?

**Comment by NghiaTranUIT** [comment]
Hi @LarsJK
I'm currently working on this feature, it's almost done. It also fulfills @khoiln's recommendation.

My approach is 
+ PersistentHandler is responsible to handle all disk-related task, such as Write, CreateFolder, Receive, etc. 
+ DiskStorage is responsible for the external Business Logic. It could be File Expiration, Max Size, and certain attribute rule for each file. It also has ability to fetch/add/remove individual file instead of the whole _interalStorage.

You can take a look at https://github.com/khoiln/swift-statsd-client/tree/disk_storage

**Comment by LarsJK** [comment]
Cool, I'll just close this PR then!

**Pull request closed without merging**
