### PR TITLE
Add Cocoapods support

### LINKED ISSUE #5: Add support for Cocoapods

### PR DESCRIPTION
**Pull request by dylanmaryk**
Fixes #5

### CODE REVIEW

**Comment by khoi** [comment]
@dylanmaryk Thank you for your contribution, the branch need a rebase though.

**Comment by dylanmaryk** [comment]
@khoiln Fixed!

**Comment by khoi** [comment]
By supporting Cocoapods, we actually mean the the users should be able to install `swift-statsd-client` via Cocoapod. 
https://guides.cocoapods.org/making/making-a-cocoapod.html
Since it's going to require some credentials, I'll take over the task and do it.
Thank you for your time :)

**Comment by dylanmaryk** [comment]
@khoiln OK, but wouldn't this still be worth having as well?

**Pull request closed without merging**
